#!/bin/sh

# Daemons can now be stopped in any order and to prove it we randomize
# the stopping of them...
#

# handle the snapmanagerdaemon with a STOP signal
# the snapstop sends a signal (SIGTERM) which is forbidden when you are
# a developer because the process runs as root
#
if test -f tmp/snapmanagerdaemon.pid
then
	echo "snapsignal snapmanagerdaemon/STOP"
	BUILD/snapwebsites/snapcommunicator/src/snapsignal "snapmanagerdaemon/STOP"
	rm -f tmp/snapmanagerdaemon.pid
fi

ALL_PIDS=`ls tmp/*.pid | shuf`

for pid_file in $ALL_PIDS
do
	# Dynamic variable selection in Bourne Shell (and others)
	#
	PID=`cat $pid_file`

	# Now start the command
	#
	echo "snapstop --service $PID # from $pid_file"
	BUILD/snapwebsites/snapcommunicator/src/snapstop --service $PID
	rm -f $pid_file
done


