#!/bin/sh
#
# Verify that fail2ban-client is not running forever
# If it is, then we've got to kill it
# This may be fixed in newer versions (0.10.x) but at the same time what is
# fixed in 0.10.x is the slow quit process
#
################################################################################
#
# Copyright (c) 2018-2019  Made to Order Software Corp.  All Rights Reserved
#
# https://snapwebsites.org/
# contact@m2osw.com
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#


set -e

FAIL2BAN_CLIENT_RUNNING="${WATCHDOG_WATCHSCRIPTS_OUTPUT}/firewall-fail2ban-client-running.txt"

# is the offensive process running?
#
# Note that fail2ban-client is a python script so we have to make sure to
# test for that special case
#
if find_process --regex --script 'python[0-9]*' fail2ban-client
then
    if test -f ${FAIL2BAN_CLIENT_RUNNING}
    then
        # the file already exists, how old?
        #
        if test "`find ${FAIL2BAN_CLIENT_RUNNING} -mmin +3`"
        then
            # problem, it has been running for 3 minutes or more
            #
            echo "warning: we detected the fail2ban-client has been running for 3 or more" >&2
            echo "minutes in a row. Please check this system as it is likely that the" >&2
            echo "utility is jammed and needs to be killed." >&2
            exit 2
        fi
    else
        # create the file
        #
        touch -f ${FAIL2BAN_CLIENT_RUNNING}
    fi
else
    # process is gone, make sure the file is gone too
    #
    rm -f ${FAIL2BAN_CLIENT_RUNNING}
fi

exit 0

# vim: ts=4 sw=4 et
