#!/bin/sh

# $1 = computer name
if test -z "$1"
then
	echo "$0 <computer name>" >&2
	exit 1
fi

# get the list of date/ips

if test ! -f /tmp/ips-$1.txt || test -n "$2"
then
	snapdb --no-types --host 10.134.28.122 firewall $1 >/tmp/ips-$1.txt
else
	echo "warning: using cached IP addresses." >&2
fi

COUNT=0
while read -r line
do
	DATE=`echo $line | awk '{ print $1 $2; }'`
	TIMESTAMP=`echo $line | awk '{ print $3; }'`
	IP=`echo $line | awk '{ print $5 }' | sed -e 's/[a-z]\+:\/\///'`

	GOOD=true
	if snapdb --no-types --host 10.134.28.122 firewall ip::$IP $1::block_limit >/tmp/info.txt
	then
		BLOCK_LIMIT=`cat /tmp/info.txt | awk '{ print $3 }'`

		if test "$TIMESTAMP" != "$BLOCK_LIMIT"
		then
			echo "error:$COUNT:no reference for IP \"$IP\" (1): $line"
			GOOD=false
		fi
	else
		echo "error:$COUNT:no reference for IP \"$IP\" (2): $line"
		GOOD=false
	fi

	if ! $GOOD
	then
		# Wehther this returns an error or not, the cell may stick
		snapdb --drop-cell --host 10.134.28.122 firewall $1 "$DATE"

		# so we want to also run cqlsh
		cqlsh --ssl -e "DELETE FROM snap_websites.firewall WHERE key = textAsBlob('$1') AND column1 = bigintAsBlob$TIMESTAMP;"
	fi

	COUNT=`expr $COUNT + 1`

	# make it easier on the database...
	sleep 3
done < /tmp/ips-$1.txt

