#!/bin/sh
#
# Whenever we recompile, we destroy the snapmanagerdaemon setup so one
# can use this script to setup the daemon again.
#
# If you are not working on the daemon, you probably want to copy it
# it somewhere else and run these commands against that copy. This way
# you can avoid having to re-run this script every single time.
#
sudo chown root ../../BUILD/snapwebsites/snapmanager/daemon/snapmanagerdaemon
sudo chmod 4775 ../../BUILD/snapwebsites/snapmanager/daemon/snapmanagerdaemon

# The snapmanager.cgi also makes use of snappassword which must be in your
# Apache2 instance path (or create a soft link from /usr/bin to your
# developer instance)
#
sudo chown root ../../BUILD/snapwebsites/snapmanager/password/snappassword
sudo chmod 4775 ../../BUILD/snapwebsites/snapmanager/password/snappassword

# We also need a few files in specific locations, this works for me, you
# may have to tweak a few things depending on your installation
#
cp snapmanager/conf/snapmanagercgi.js /usr/clients/www/csnap.m2osw.com/public_html/.
cp snapmanager/conf/snapmanagercgi.css /usr/clients/www/csnap.m2osw.com/public_html/.
cp snapmanager/conf/snapmanagercgi-parser.xsl /etc/snapwebsites/.
cp ../../BUILD/snapwebsites/snapmanager/cgi/snapmanager.cgi /usr/clients/www/csnap.m2osw.com/cgi-bin/snapmanager.cgi

# vim: ts=4 sw=4 et
