#!/bin/sh
#
# Whenever we recompile, we destroy the snapmanagerdaemon setup so one
# can use this script to setup the daemon again.
#
# If you are not working on the daemon, you probably want to copy it
# it somewhere else and run these commands against that copy. This way
# you can avoid having to re-run this script every single time.
#
sudo chown root ../../BUILD/snapwebsites/snapmanager/daemon/snapmanagerdaemon
sudo chmod 4775 ../../BUILD/snapwebsites/snapmanager/daemon/snapmanagerdaemon

# The snapmanager.cgi also makes use of snappassword which must be in your
# Apache2 instance path (or create a soft link from /usr/bin to your
# developer instance)
#
sudo chown root ../../BUILD/snapwebsites/snapmanager/password/snappassword
sudo chmod 4775 ../../BUILD/snapwebsites/snapmanager/password/snappassword
