#!/bin/sh
#
# sendmail script to capture the email::send() calls so we can verify that
# emails being sent are sent properly
#
# Copyright (c) 2014-2019  Made to Order Software Corp.  All Rights Reserved
#
# https://snapwebsites.org/
# contact@m2osw.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

if test "$1" != "-f"
then
    echo "error: -f expected as the first command line option"
    exit 1;
fi

if test -z "$2"
then
    # We could check validity with `validate_tld` from libtld,
    # I'm just not too sure how to access that right now
    #
    echo "error: second parameter (after -f) must be the source email address (at least it has to be non-empty)"
    exit 1;
fi
FROM="$2"

if test -z "$3"
then
    echo "error: third parameter must be the destination email address"
    exit 1;
fi
TO="$3"

email=/tmp/email.eml
echo "From $FROM" >$email

# Copy the incoming data up to the lone period
while IFS= read -r LINE
do
    if test "$LINE" = "."
    then
        break;
    fi
    printf '%s\n' "$LINE" >>$email
done

# vim: ts=4 sw=4 et
