#!/bin/sh
#
# Mark a website as ready in case a tool failed and the website is
# in a "weird" state (i.e. marked as not ready.)

while test "$1" != ""
do
	case "$1" in
	--help|-h)
		echo "Usage: `basename $0` --host <IP to database> --uri <website home page>"
		echo
		exit 1
		;;

	--host)
		HOST="$1"
		;;

	--uri)
		URI="$1"
		;;

	*)
		echo "error: Unknown command line option \"$1\""
		echo "error: try --help for usage information"
		exit 1
		;;

	esac
done

# The following command will fail the site was not yet initialized because
# the row will not exist; DO NOT ADD THE --create-row, instead you want to
# run snapinstallwebsite
#
snapdb --host $HOST sites $URI core::site_state "ready"
