#!/bin/bash
#
# Run all the snapdatabase tests with coverage
#
# Copyright (c) 2019  Made to Order Software Corp.  All Rights Reserved
#
# https://snapwebsites.org/project/snapdatabase
# contact@m2osw.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

set -e

if test "$1" = "--help" -o "$1" = "-h"
then
    echo "Usage: $0 [--opt] [test-name]"
    echo "where --opt is one of:"
    echo "   --help | -h    display this help screen"
    echo "   test-name      the name of a test; if not specified, all tests"
    exit 1;
fi

PROCESSORS=`nproc`

TEST_NAME=
if test -n "$1"
then
    TEST_NAME="$1"
    shift
fi


start_date=`date`
SOURCE=`pwd`
VERSION=`dpkg-parsechangelog --show-field Version | sed -e 's/~.*//' -e 's/\(^[0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/'`
echo "***"
echo "*** snapdatabase coverage for version $VERSION ($start_date)"
echo "***"
mkdir -p snapdatabase/tmp/coverage
rm -rf snapdatabase/tmp/coverage/*
cd snapdatabase/tmp/coverage
mkdir BUILD
cd BUILD
# request coverage in this build
dist=`cd ../../../../../../; pwd`/BUILD/dist
modules=$dist/share/cmake-3.5/Modules
cmake -DCMAKE_INSTALL_PREFIX:PATH=$dist \
    -DCMAKE_MODULE_PATH:PATH=$modules \
    -DCMAKE_BUILD_TYPE=Debug \
    -Dsnapwebsites_top_dir_COVERAGE:BOOL=ON \
    ../../../.. \
        | tee cmake.log
cd ..
echo
echo "***"
echo "*** compile (`date`)"
echo "***"
VERBOSE=1 make -j ${PROCESSORS} -C BUILD
echo
echo "***"
echo "*** run (`date`)"
echo "***"
if test `BUILD/snapdatabase/tests/unittest --version` != "$VERSION"
then
    echo "the version of unittest (`BUILD/tests/unittest --version`) is not equal to the project version ($VERSION)"
    exit 1;
fi

# We test the pipe status on exit to detect whether the test failed
echo "Start running the tests on `date`" >test_log.txt
echo >>test_log.txt
mkdir -p tmp/context
BUILD/snapdatabase/tests/unittest "${TEST_NAME}" -T tmp/context --progress 2>&1 | tee -a test_log.txt; test ${PIPESTATUS[0]} -eq 0
echo >>test_log.txt
echo "Finished running the tests on `date`" >>test_log.txt
echo
echo "***"
echo "*** gcov/lcov (`date`)"
echo "***"

# Choose one of the following gcov commands
#mkdir -p gcov
#cd gcov
#gcov -o ../BUILD/src/CMakeFiles/snapdatabase.dir/context.cpp.gcno ../../../src/context.cpp
#cd ..


#lcov --capture --directory BUILD --output-file coverage.info
# The following lcov options can be used under Ubuntu 14.04+
# Use --no-external and --base-directory $SOURCE
# to avoid /usr/include and other unwanted files
# (only available in lcov version 1.10+)
lcov --capture --no-external --directory BUILD --base-directory $SOURCE --output-file coverage.info
mkdir -p html
genhtml --legend --demangle-cpp --no-branch-coverage --show-details coverage.info --output-directory html


end_date=`date`

# Statistics
echo "<html><head><title>snapdatabase $VERSION statistics</title></head><body>" >html/statistics.html
echo "<h3>Statistics of the snapdatabase $VERSION library</h3><pre>" >>html/statistics.html
cloc $SOURCE/snapdatabase/ >>html/statistics.html
echo "</pre><h3>Statistics of the snapdatabase $VERSION tests</h3><pre>" >>html/statistics.html
cloc $SOURCE/tests/ >>html/statistics.html
#echo "</pre><h3>Statistics of snapdatabase tools $VERSION</h3><pre>" >>html/statistics.html
#cloc $SOURCE/tools/ >>html/statistics.html
echo "</pre></body></html>" >>html/statistics.html

# Test output (Logs)
echo "<html><head><title>snapdatabase $VERSION test logs</title></head><body><h3>Logs for the snapdatabase $VERSION tests</h3><p>Tests started on $start_date and finished on $end_date</p><pre>" >html/test_log.html
if test -f test_log.txt
then
    # If test_log.txt does not exist, the user got the logs in the
    # console already
    cat test_log.txt >>html/test_log.html
fi
echo "</pre></body></html>" >>html/test_log.html


# For publication, if that directory does not exist, you probably don't
# have a website to display this data
PUBLISH_DIR=/usr/clients/www/lcov.snapwebsites.org/public_html
if test -z "${TEST_NAME}" -a -d ${PUBLISH_DIR}
then
    echo "***"
    echo "*** publication to lcov.snapwebsites.org ($end_date)"
    echo "***"

    # Create folder for this specific version
    mkdir -p ${PUBLISH_DIR}/snapdatabase/snapdatabase-$VERSION

    # Make sure we have the latest index
    cp $SOURCE/snapdatabase/dev/index.php ${PUBLISH_DIR}/snapdatabase

    # Copy coverage and statistics HTML results
    cp -r html/* ${PUBLISH_DIR}/snapdatabase/snapdatabase-$VERSION/.
fi

echo "Process started  on $start_date"
echo "Process finished on $end_date"

# vim: ts=4 sw=4 et
