debian/tmp/usr/sbin/snaplock                                  usr/sbin/
debian/tmp/usr/lib/snapwebsites/manager_plugins/liblock.so    usr/lib/snapwebsites/manager_plugins/
debian/tmp/usr/share/snapwebsites/logger/snaplock.properties  usr/share/snapwebsites/logger/
snaplock/conf/snaplock.conf                                   etc/snapwebsites/
snaplock/conf/snaplock.properties                             etc/snapwebsites/logger/
