debian/tmp/usr/sbin/snaplog                                                     usr/sbin/
debian/tmp/usr/share/snapwebsites/snapwatchdog/processes/snaplog-processes.xml  usr/share/snapwebsites/snapwatchdog/processes/
debian/tmp/usr/share/snapwebsites/logger/snaplog.properties                     usr/share/snapwebsites/logger/
snaplog/conf/snaplog.properties                                                 etc/snapwebsites/logger/
snaplog/conf/snaplog.conf                                                       etc/snapwebsites/
snaplog/conf/snap-mysql-jail.conf                                               etc/fail2ban/jail.d/
