debian/tmp/usr/bin/cxpath                                                usr/bin/
debian/tmp/usr/bin/snapexpr                                              usr/bin/
debian/tmp/usr/bin/snapimg                                               usr/bin/
debian/tmp/usr/bin/snapserver                                            usr/bin/
debian/tmp/usr/lib/snapwebsites/manager_plugins/libsnapserver_manager.so usr/lib/snapwebsites/manager_plugins/
