debian/tmp/usr/bin/snaplistd                                                      usr/bin/
debian/tmp/usr/share/snapwebsites/snapwatchdog/processes/snaplistd-processes.xml  usr/share/snapwebsites/snapwatchdog/processes/
snaplistd/conf/snaplistd.conf                                                     etc/snapwebsites/
snaplistd/conf/snaplistd.properties                                               etc/snapwebsites/logger/
