.TH "snapclusterstatus" 1 "Sat Apr 20 2019" "Version 1.7.7" "snapcommunicator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
snapclusterstatus - query snapcommunicator about the cluster status
.SH SYNOPSIS
.B snapclusterstatus
[\fB--help\fR] [\fB--version\fR] [\fB\-c|\-\-config\fR \fI\,config\/\fR]
.SH DESCRIPTION

The \fBsnapclusterstatus\fR sends a \fBCLUSTERSTATUS\fR message to the
\fBsnapcommunicator\fR daemon, prints out the results, and exits.

If the \fBsnapcommunicator\fR daemon is not running, then an error
occurs and corresponding messages are printed.

By default the \fBsnapclusterstatus\fR uses the configuration information
found in \fB/etc/snapwebsites/snapcommunicator.conf\fR and 
\fB/etc/snapwebsites/snapwebsites.d/snapcommunicator.conf\fR. The filename
can be used using the \fB--config\fR option.

The command supports the following options:

.TP
\fB\-\-help
prints out the help page

.TP
\fB\-\-version
prints out the version (which is really snapcommunicator's version)

.TP
\fB\-\-config | \-c \fI\,config\/\fR
specify a different configuration file than the default.

.SH AUTHOR

Written by Alexis Wilke, based on snaplock.

.SH REPORTING BUGS

https://github.com/m2osw/snapwebsites/issues

.SH COPYRIGHT

Copyright (c) 2019  Made to Order Software Corp.
License GPLv2+.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
Full documentation at: <http://snapwebsites.org/>
