#!/bin/sh
#

OUTPUT="$1/js-compile"
mkdir -p $OUTPUT

#

OPTIONS="--warning_level VERBOSE"

       # At this point the extensions doesn't work right because the
       # expr is not defined in the jquery definitions
       #plugins/output/jquery-extensions.js

       # This file is empty by default, the system generates the contents
       # when the user downloads it (it is 100% dynamic, we will have to
       # check for the cache settings when those get turned on though...)
       #plugins/ecommerce/ecommerce-cart.js

       # The favicon editor JavaScript is a 3rd party script that I keep
       # here as an example. We will create our own Editor widget instead.
       #plugins/favicon/favicon-editor.js

       # This file is automatically generated, we do not really care too
       # much about checking such with the closure compiler.
       #plugins/mimetype/mimetype-basics.js

       # This file is generated each time a new version of Qt is made
       # available to Snap! Websites; especially if that newer version
       # was compiled with a newer version of Unicode
       #plugins/output/javascript-unicode.js

       # This file is a 3rd party JavaScript and we do not test these here
       #plugins/sortable/sortable.js

FILES="plugins/bookkeeping/bookkeeping-add-client.js
       plugins/bookkeeping/bookkeeping-client.js
       plugins/date_widgets/date_widgets/date-widgets.js
       plugins/ecommerce/ecommerce.js
       plugins/editor/editor.js
       plugins/epayment/epayment.js
       plugins/epayment_creditcard/epayment-credit-card.js
       plugins/epayment_creditcard/epayment-credit-card-form.js
       plugins/epayment_paypal/epayment-paypal.js
       plugins/epayment_stripe/epayment-stripe.js
       plugins/favicon/favicon.js
       plugins/flash/flash-detection.js
       plugins/form/form.js
       plugins/info/plugin-selection/plugin-selection.js
       plugins/info/sendmail/unsubscribe.js
       plugins/listener/listener.js
       plugins/list/list/list.js
       plugins/locale_widgets/locale-timezone.js
       plugins/output/fixed-box.js
       plugins/output/output.js
       plugins/output/popup.js
       plugins/output/rotate-animation.js
       plugins/password/password.js
       plugins/password/password-blacklist.js
       plugins/permissions/remove-iframe-for-login.js
       plugins/server_access/server-access.js
       plugins/sortable/sortable-widgets.js
       plugins/test_plugin/test-plugin.js
       plugins/timetracker/timetracker/timetracker.js
       plugins/users/users.js"

CLOSURE_COMPILER=/home/snapwebsites/tmp/google-js-compiler/closure-compiler

for js in $FILES
do
    INLINE_OPTIONS_WITH_VARS=`sed \
        -e '0,/==ClosureCompiler==/ d' \
        -e '/==\/ClosureCompiler==/,$ d' \
        -e 's/.*@\(.*\)/--\1/' $js`

    INLINE_OPTIONS=`echo $INLINE_OPTIONS_WITH_VARS | sed \
        -e "s:\\\$CLOSURE_COMPILER:$CLOSURE_COMPILER:g"`

    cmd="java -jar ../tmp/google-js-compiler/compiler.jar --js_output_file $OUTPUT/`basename $js .js`.min.js $OPTIONS $INLINE_OPTIONS --js $js"
    echo "$js:"
    echo $cmd
    $cmd
done

# TBD not too sure why but the compiler always returns an error...
exit 0
# vim: ts=4 sw=4 et
